clc;
clear;
load('D:\Derek\Matlab\runningModule_V2\MatlabFiles\data\test_vimove2_int\data3.mat');

%%
data_Left = data_left';
data_Right = data_right';
Stc = time;
BodyMass = 90;



[GRF_Left, GRF_Vector_Left, IPA_Left, IPA_Vector_Left, ...
    GRF_Right, GRF_Vector_Right, IPA_Right, IPA_Vector_Right, ...
    ContactTime_Left, ContactTimeVector_Left,...
    ContactTime_Right, ContactTimeVector_Right,...
    Speed, SpeedVector,Distance, DistanceVector,...
    Cadence, CadenceVector, RunTime, StrideNumber,...
    ASI,ASI_Vector,time_L,time_R] = ...
    estimateMetrics(Stc, BodyMass, data_Left, data_Right, 6);

