function [acc,gyro,mag,high_g_acc,high_speed_gyro,emg,...
    battery_voltage,battery_soc,acc_temp,mag_temp,...
    timeTZ,timeHighG,timeHsGyro,timeEmg] = qu_file_v6c(filename)
% filename = 'D:\Derek\Matlab\EKFProcessFileDLL\EKFprocessFileDLL\data\alan\mdm0002-25.bin';
m = memmapfile(filename);
A = m.Data;
[accx,accy,accz,magx,magy,magz,gyrox,gyroy,gyroz,...
    high_g_interpx,high_g_interpy,high_g_interpz,...
    battery_soc,battery_voltage,timeTZ,timeHighG,timeHsGyro,...
    emg,timeEmg,acc_temp,mag_temp,hsGyro_interpx,hsGyro_interpy,hsGyro_interpz] =...
 process_bin(A',4,250,500,49,500);

acc = [accx' accy' accz'];
gyro = [gyrox' gyroy' gyroz'];
mag = [magx' magy' magz'];
high_g_acc = [high_g_interpx' high_g_interpy' high_g_interpz'];
high_speed_gyro = [hsGyro_interpx' hsGyro_interpy' hsGyro_interpz'];

end